// lib/widgets/country_codes.dart
// Shared worldwide dialing-code list used by every phone input across the app.
// Keep this as the single source of truth so all forms stay consistent.

class Country {
  final String flag;
  final String code; // e.g. "+92"
  final String name;

  const Country({required this.flag, required this.code, required this.name});
}

const String kDefaultDialCode = '+92';
const String kDefaultDialFlag = '🇵🇰';

const List<Country> kCountryCodes = [
  Country(flag: '🇵🇰', code: '+92', name: 'Pakistan'),
  Country(flag: '🇦🇪', code: '+971', name: 'UAE'),
  Country(flag: '🇸🇦', code: '+966', name: 'Saudi Arabia'),
  Country(flag: '🇺🇸', code: '+1', name: 'United States'),
  Country(flag: '🇬🇧', code: '+44', name: 'United Kingdom'),
  Country(flag: '🇮🇳', code: '+91', name: 'India'),
  Country(flag: '🇧🇩', code: '+880', name: 'Bangladesh'),
  Country(flag: '🇦🇫', code: '+93', name: 'Afghanistan'),
  Country(flag: '🇦🇱', code: '+355', name: 'Albania'),
  Country(flag: '🇩🇿', code: '+213', name: 'Algeria'),
  Country(flag: '🇦🇴', code: '+244', name: 'Angola'),
  Country(flag: '🇦🇷', code: '+54', name: 'Argentina'),
  Country(flag: '🇦🇲', code: '+374', name: 'Armenia'),
  Country(flag: '🇦🇺', code: '+61', name: 'Australia'),
  Country(flag: '🇦🇹', code: '+43', name: 'Austria'),
  Country(flag: '🇦🇿', code: '+994', name: 'Azerbaijan'),
  Country(flag: '🇧🇭', code: '+973', name: 'Bahrain'),
  Country(flag: '🇧🇾', code: '+375', name: 'Belarus'),
  Country(flag: '🇧🇪', code: '+32', name: 'Belgium'),
  Country(flag: '🇧🇷', code: '+55', name: 'Brazil'),
  Country(flag: '🇧🇳', code: '+673', name: 'Brunei'),
  Country(flag: '🇧🇬', code: '+359', name: 'Bulgaria'),
  Country(flag: '🇨🇦', code: '+1', name: 'Canada'),
  Country(flag: '🇨🇱', code: '+56', name: 'Chile'),
  Country(flag: '🇨🇳', code: '+86', name: 'China'),
  Country(flag: '🇨🇴', code: '+57', name: 'Colombia'),
  Country(flag: '🇭🇷', code: '+385', name: 'Croatia'),
  Country(flag: '🇨🇾', code: '+357', name: 'Cyprus'),
  Country(flag: '🇨🇿', code: '+420', name: 'Czech Republic'),
  Country(flag: '🇩🇰', code: '+45', name: 'Denmark'),
  Country(flag: '🇪🇬', code: '+20', name: 'Egypt'),
  Country(flag: '🇪🇹', code: '+251', name: 'Ethiopia'),
  Country(flag: '🇫🇮', code: '+358', name: 'Finland'),
  Country(flag: '🇫🇷', code: '+33', name: 'France'),
  Country(flag: '🇩🇪', code: '+49', name: 'Germany'),
  Country(flag: '🇬🇭', code: '+233', name: 'Ghana'),
  Country(flag: '🇬🇷', code: '+30', name: 'Greece'),
  Country(flag: '🇭🇰', code: '+852', name: 'Hong Kong'),
  Country(flag: '🇭🇺', code: '+36', name: 'Hungary'),
  Country(flag: '🇮🇩', code: '+62', name: 'Indonesia'),
  Country(flag: '🇮🇷', code: '+98', name: 'Iran'),
  Country(flag: '🇮🇶', code: '+964', name: 'Iraq'),
  Country(flag: '🇮🇪', code: '+353', name: 'Ireland'),
  Country(flag: '🇮🇱', code: '+972', name: 'Israel'),
  Country(flag: '🇮🇹', code: '+39', name: 'Italy'),
  Country(flag: '🇯🇵', code: '+81', name: 'Japan'),
  Country(flag: '🇯🇴', code: '+962', name: 'Jordan'),
  Country(flag: '🇰🇿', code: '+7', name: 'Kazakhstan'),
  Country(flag: '🇰🇪', code: '+254', name: 'Kenya'),
  Country(flag: '🇰🇼', code: '+965', name: 'Kuwait'),
  Country(flag: '🇱🇧', code: '+961', name: 'Lebanon'),
  Country(flag: '🇱🇾', code: '+218', name: 'Libya'),
  Country(flag: '🇲🇾', code: '+60', name: 'Malaysia'),
  Country(flag: '🇲🇻', code: '+960', name: 'Maldives'),
  Country(flag: '🇲🇽', code: '+52', name: 'Mexico'),
  Country(flag: '🇲🇦', code: '+212', name: 'Morocco'),
  Country(flag: '🇳🇵', code: '+977', name: 'Nepal'),
  Country(flag: '🇳🇱', code: '+31', name: 'Netherlands'),
  Country(flag: '🇳🇿', code: '+64', name: 'New Zealand'),
  Country(flag: '🇳🇬', code: '+234', name: 'Nigeria'),
  Country(flag: '🇳🇴', code: '+47', name: 'Norway'),
  Country(flag: '🇴🇲', code: '+968', name: 'Oman'),
  Country(flag: '🇵🇭', code: '+63', name: 'Philippines'),
  Country(flag: '🇵🇱', code: '+48', name: 'Poland'),
  Country(flag: '🇵🇹', code: '+351', name: 'Portugal'),
  Country(flag: '🇶🇦', code: '+974', name: 'Qatar'),
  Country(flag: '🇷🇴', code: '+40', name: 'Romania'),
  Country(flag: '🇷🇺', code: '+7', name: 'Russia'),
  Country(flag: '🇷🇼', code: '+250', name: 'Rwanda'),
  Country(flag: '🇸🇳', code: '+221', name: 'Senegal'),
  Country(flag: '🇷🇸', code: '+381', name: 'Serbia'),
  Country(flag: '🇸🇬', code: '+65', name: 'Singapore'),
  Country(flag: '🇿🇦', code: '+27', name: 'South Africa'),
  Country(flag: '🇰🇷', code: '+82', name: 'South Korea'),
  Country(flag: '🇪🇸', code: '+34', name: 'Spain'),
  Country(flag: '🇱🇰', code: '+94', name: 'Sri Lanka'),
  Country(flag: '🇸🇩', code: '+249', name: 'Sudan'),
  Country(flag: '🇸🇪', code: '+46', name: 'Sweden'),
  Country(flag: '🇨🇭', code: '+41', name: 'Switzerland'),
  Country(flag: '🇸🇾', code: '+963', name: 'Syria'),
  Country(flag: '🇹🇼', code: '+886', name: 'Taiwan'),
  Country(flag: '🇹🇿', code: '+255', name: 'Tanzania'),
  Country(flag: '🇹🇭', code: '+66', name: 'Thailand'),
  Country(flag: '🇹🇳', code: '+216', name: 'Tunisia'),
  Country(flag: '🇹🇷', code: '+90', name: 'Turkey'),
  Country(flag: '🇺🇬', code: '+256', name: 'Uganda'),
  Country(flag: '🇺🇦', code: '+380', name: 'Ukraine'),
  Country(flag: '🇺🇿', code: '+998', name: 'Uzbekistan'),
  Country(flag: '🇻🇳', code: '+84', name: 'Vietnam'),
  Country(flag: '🇾🇪', code: '+967', name: 'Yemen'),
  Country(flag: '🇿🇲', code: '+260', name: 'Zambia'),
  Country(flag: '🇿🇼', code: '+263', name: 'Zimbabwe'),
];
